apiVersion: v1
kind: Pod
metadata:
  name: cpus-java
spec:
  containers:
  - name: cpus-java
    image: volkerraschek/cpus-java
    imagePullPolicy: Always
    resources:
      requests:
        memory: 512M
        cpu: 1
      limits:
        memory: 2Gi
        cpu: 1
  restartPolicy: Always